import type { Work } from "@/lib/mockData";

export type MyProjectWork = Work & {
  source: string;
  authorizedForWall: boolean;
  authorizedForPromo: boolean;
};

export const myProjectsWorks: MyProjectWork[] = [
  {
    id: "my-project-001",
    title: "《24南堂界遇徽章》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/24%E5%8D%97%E5%A0%82%E7%95%8C%E9%81%87%E5%BE%BD%E7%AB%A0.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-002",
    title: "《24年东方南堂界遇海报》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/24%E5%B9%B4%E4%B8%9C%E6%96%B9%E5%8D%97%E5%A0%82%E7%95%8C%E9%81%87%E6%B5%B7%E6%8A%A5.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-003",
    title: "《阿求30岁》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E9%98%BF%E6%B1%8230%E5%B2%81.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-004",
    title: "《翠香草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%BF%A0%E9%A6%99%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-005",
    title: "《东方幼灵梦印象图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E4%B8%9C%E6%96%B9%E5%B9%BC%E7%81%B5%E6%A2%A6%E5%8D%B0%E8%B1%A1%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-006",
    title: "《风见幽香》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E9%A3%8E%E8%A7%81%E5%B9%BD%E9%A6%99.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-007",
    title: "《芙兰乐队草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E8%8A%99%E5%85%B0%E4%B9%90%E9%98%9F%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-008",
    title: "《华扇草原色草》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8D%8E%E6%89%87%E8%8D%89%E5%8E%9F%E8%89%B2%E8%8D%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-009",
    title: "《华扇色草》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8D%8E%E6%89%87%E8%89%B2%E8%8D%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-010",
    title: "《欢迎来到守矢神社》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%E5%AE%88%E7%9F%A2%E7%A5%9E%E7%A4%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-011",
    title: "《幻想入侵——守矢诹访纪行》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%B9%BB%E6%83%B3%E5%85%A5%E4%BE%B5%E2%80%94%E2%80%94%E5%AE%88%E7%9F%A2%E8%AF%B9%E8%AE%BF%E7%BA%AA%E8%A1%8C.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-012",
    title: "《黄昏俱乐部》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E9%BB%84%E6%98%8F%E4%BF%B1%E4%B9%90%E9%83%A8.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-013",
    title: "《觉恋春日草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E8%A7%89%E6%81%8B%E6%98%A5%E6%97%A5%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-014",
    title: "《狂气魔术兔（25.1合作明信片）》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%8B%82%E6%B0%94%E9%AD%94%E6%9C%AF%E5%85%94%EF%BC%8825.1%E5%90%88%E4%BD%9C%E6%98%8E%E4%BF%A1%E7%89%87%EF%BC%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-015",
    title: "《蕾蒂》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E8%95%BE%E8%92%82.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-016",
    title: "《蕾米乐队草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E8%95%BE%E7%B1%B3%E4%B9%90%E9%98%9F%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-017",
    title: "《莲子七夕坂草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E8%8E%B2%E5%AD%90%E4%B8%83%E5%A4%95%E5%9D%82%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-018",
    title: "《米斯缇娅》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%B1%B3%E6%96%AF%E7%BC%87%E5%A8%85.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-019",
    title: "《秘封华尔兹草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%A7%98%E5%B0%81%E5%8D%8E%E5%B0%94%E5%85%B9%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-020",
    title: "《秘封铁塔（羊学产物）》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%A7%98%E5%B0%81%E9%93%81%E5%A1%94%EF%BC%88%E7%BE%8A%E5%AD%A6%E4%BA%A7%E7%89%A9%EF%BC%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-021",
    title: "《秘封in交大1》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%A7%98%E5%B0%81in%E4%BA%A4%E5%A4%A71.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-022",
    title: "《秘封in交大2》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%A7%98%E5%B0%81in%E4%BA%A4%E5%A4%A72.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-023",
    title: "《秘封in交大3》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%A7%98%E5%B0%81in%E4%BA%A4%E5%A4%A73.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-024",
    title: "《秘封in交大4草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%A7%98%E5%B0%81in%E4%BA%A4%E5%A4%A74%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-025",
    title: "《纳兹铃》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%BA%B3%E5%85%B9%E9%93%83.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-026",
    title: "《帕露西草图 (2)》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%B8%95%E9%9C%B2%E8%A5%BF%E8%8D%89%E5%9B%BE%20(2).png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-027",
    title: "《帕露西草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%B8%95%E9%9C%B2%E8%A5%BF%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-028",
    title: "《帕琪乐队草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%B8%95%E7%90%AA%E4%B9%90%E9%98%9F%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-029",
    title: "《千年组（早期创作）》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8D%83%E5%B9%B4%E7%BB%84%EF%BC%88%E6%97%A9%E6%9C%9F%E5%88%9B%E4%BD%9C%EF%BC%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-030",
    title: "《千年组飞我去星》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8D%83%E5%B9%B4%E7%BB%84%E9%A3%9E%E6%88%91%E5%8E%BB%E6%98%9F.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-031",
    title: "《千年组樱花重逢》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8D%83%E5%B9%B4%E7%BB%84%E6%A8%B1%E8%8A%B1%E9%87%8D%E9%80%A2.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-032",
    title: "《千年组重逢》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8D%83%E5%B9%B4%E7%BB%84%E9%87%8D%E9%80%A2.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-033",
    title: "《千亦色草》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8D%83%E4%BA%A6%E8%89%B2%E8%8D%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-034",
    title: "《神明的落日》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%A5%9E%E6%98%8E%E7%9A%84%E8%90%BD%E6%97%A5.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-035",
    title: "《守矢叠叠乐》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%AE%88%E7%9F%A2%E5%8F%A0%E5%8F%A0%E4%B9%90.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-036",
    title: "《守矢家（早期创作）》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%AE%88%E7%9F%A2%E5%AE%B6%EF%BC%88%E6%97%A9%E6%9C%9F%E5%88%9B%E4%BD%9C%EF%BC%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-037",
    title: "《守矢家2（早期创作）》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%AE%88%E7%9F%A2%E5%AE%B62%EF%BC%88%E6%97%A9%E6%9C%9F%E5%88%9B%E4%BD%9C%EF%BC%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-038",
    title: "《守矢手牵手》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%AE%88%E7%9F%A2%E6%89%8B%E7%89%B5%E6%89%8B.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-039",
    title: "《守矢诹访纪行草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%AE%88%E7%9F%A2%E8%AF%B9%E8%AE%BF%E7%BA%AA%E8%A1%8C%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-040",
    title: "《水彩组图——芙兰》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E8%8A%99%E5%85%B0.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-041",
    title: "《水彩组图——觉草稿》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E8%A7%89%E8%8D%89%E7%A8%BF.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-042",
    title: "《水彩组图——蕾米》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E8%95%BE%E7%B1%B3.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-043",
    title: "《水彩组图——恋草稿》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E6%81%8B%E8%8D%89%E7%A8%BF.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-044",
    title: "《水彩组图——灵梦》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E7%81%B5%E6%A2%A6.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-045",
    title: "《水彩组图——魔理沙》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E9%AD%94%E7%90%86%E6%B2%99.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-046",
    title: "《水彩组图——琪露诺》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E7%90%AA%E9%9C%B2%E8%AF%BA.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-047",
    title: "《水彩组图——早苗》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E6%97%A9%E8%8B%97.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-048",
    title: "《水彩组图——紫》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%B0%B4%E5%BD%A9%E7%BB%84%E5%9B%BE%E2%80%94%E2%80%94%E7%B4%AB.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-049",
    title: "《四季映姬1h速涂》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%9B%9B%E5%AD%A3%E6%98%A0%E5%A7%AC1h%E9%80%9F%E6%B6%82.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-050",
    title: "《巫女组猫猫舞》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%B7%AB%E5%A5%B3%E7%BB%84%E7%8C%AB%E7%8C%AB%E8%88%9E.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-051",
    title: "《夏日与大海与奇迹风祝》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%A4%8F%E6%97%A5%E4%B8%8E%E5%A4%A7%E6%B5%B7%E4%B8%8E%E5%A5%87%E8%BF%B9%E9%A3%8E%E7%A5%9D.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-052",
    title: "《咲夜乐队草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%92%B2%E5%A4%9C%E4%B9%90%E9%98%9F%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-053",
    title: "《笑颜早苗》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E7%AC%91%E9%A2%9C%E6%97%A9%E8%8B%97.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-054",
    title: "《妖妖梦飞我去星描改》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%A6%96%E5%A6%96%E6%A2%A6%E9%A3%9E%E6%88%91%E5%8E%BB%E6%98%9F%E6%8F%8F%E6%94%B9.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-055",
    title: "《鵺草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E9%B5%BA%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-056",
    title: "《勇仪草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E5%8B%87%E4%BB%AA%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。","河童：这个角度蛮难画的，完成度不错。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-057",
    title: "《早苗祈愿俯视草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%97%A9%E8%8B%97%E7%A5%88%E6%84%BF%E4%BF%AF%E8%A7%86%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。","南枝：这张构图挺有感觉的，角色动作很清楚。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-058",
    title: "《早苗色草》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E6%97%A9%E8%8B%97%E8%89%B2%E8%8D%89.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。","小满：很适合放进个人练习归档。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-059",
    title: "《主角组透视草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/%E4%B8%BB%E8%A7%92%E7%BB%84%E9%80%8F%E8%A7%86%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["小满：很适合放进个人练习归档。","青禾：这张可以作为以后活动的参考图。","夜雀：线条挺顺的，能看出画的时候很有想法。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-060",
    title: "《Q版灵梦》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/Q%E7%89%88%E7%81%B5%E6%A2%A6.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 3,
    commentList: ["河童：这个角度蛮难画的，完成度不错。","小周：人物和道具关系处理得挺自然。","南枝：感觉可以做成系列图。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
  {
    id: "my-project-061",
    title: "《Q版魔理沙草图》",
    author: "我",
    authorId: "admin",
    type: "插画",
    source: "个人作品归档",
    activity: "个人作品归档",
    image: "/demo-uploads/my-projects/Q%E7%89%88%E9%AD%94%E7%90%86%E6%B2%99%E8%8D%89%E5%9B%BE.png",
    description: "测试账号的东方相关个人作品，已加入群作品墙与个人QQ空间。",
    tags: ["个人作品","东方","插画"],
    likes: 0,
    comments: 4,
    commentList: ["南枝：这张构图挺有感觉的，角色动作很清楚。","墨团：颜色氛围不错，感觉可以继续细化成完整作品。","未央：这个角色表情很抓人。","阿璃：背景如果再补一点会更完整。"],
    authorizationText: "已授权展示与宣发整理",
    syncedToQzone: true,
    activityId: "personal",
    sourceType: "my-projects",
    gradient: "from-sky-100 via-white to-violet-100",
    avatar: "管",
    avatarSrc: "/avatars/admin.png",
    authorizedForWall: true,
    authorizedForPromo: true,
  },
];

export const myProjectsSpacePosts = myProjectsWorks.map((work) => ({
  title: work.title,
  content: work.description ?? "测试账号的东方相关个人作品。",
  activity: work.source,
  likes: work.likes ?? 0,
  comments: work.comments,
  gradient: work.gradient,
  image: work.image,
  tags: work.tags,
}));
