export const reimuBirthdayAssetBase = "/works/reimu-birthday";

export const reimuBirthdayImages = {
  shrineMorningFinal: `${reimuBirthdayAssetBase}/reimu_shrine_morning_final.png`,
  shrineMorningSketch: `${reimuBirthdayAssetBase}/reimu_shrine_morning_sketch.png`,
  shrineMorningLineart: `${reimuBirthdayAssetBase}/reimu_shrine_morning_lineart.png`,
  shrineLetter: `${reimuBirthdayAssetBase}/shrine_letter_weiyang.png`,
  mangaStoryboard: `${reimuBirthdayAssetBase}/birthday_manga_storyboard.png`,
  stickerSheet: `${reimuBirthdayAssetBase}/reimu_birthday_sticker_sheet.png`,
  birthdayCake: `${reimuBirthdayAssetBase}/birthday_cake_by_saisenbako.png`,
  giftChecklist: `${reimuBirthdayAssetBase}/gift_checklist_page.png`,
  anthologyStoryboard: `${reimuBirthdayAssetBase}/anthology_cover_storyboard.png`,
  anthologyCover: `${reimuBirthdayAssetBase}/reimu_birthday_anthology_cover.png`,
} as const;

export const reimuBirthdayWorks = [
  {
    title: "《神社清晨的灵梦》",
    author: "墨团",
    authorId: "motuan",
    avatar: "墨",
    type: "开场插画",
    image: reimuBirthdayImages.shrineMorningFinal,
    gradient: "from-rose-200 via-red-100 to-sky-200",
    tags: ["灵梦生日", "开场图", "最终稿"],
    description: "红白配色的主视觉开场，定下生日合辑的温柔基调。",
  },
  {
    title: "《神社清晨的灵梦》构图草稿",
    author: "墨团",
    authorId: "motuan",
    avatar: "墨",
    type: "构图草稿",
    image: reimuBirthdayImages.shrineMorningSketch,
    gradient: "from-rose-100 via-orange-100 to-sky-100",
    tags: ["灵梦生日", "过程稿", "构图"],
    description: "开场插画的构图草稿，记录门口光线和角色位置的早期安排。",
  },
  {
    title: "《神社清晨的灵梦》线稿",
    author: "墨团",
    authorId: "motuan",
    avatar: "墨",
    type: "线稿",
    image: reimuBirthdayImages.shrineMorningLineart,
    gradient: "from-rose-100 via-red-100 to-amber-100",
    tags: ["灵梦生日", "过程稿", "线稿"],
    description: "开场插画线稿，适合在活动记录里展示创作过程。",
  },
  {
    title: "《神社来信》",
    author: "未央",
    authorId: "weiyang",
    avatar: "央",
    type: "短篇文字",
    image: reimuBirthdayImages.shrineLetter,
    gradient: "from-sky-100 via-white to-rose-100",
    tags: ["短篇", "神社", "信件页"],
    description: "从灵梦收到来信前的独白切入，把接力作品串成一份礼物。",
  },
  {
    title: "《生日小漫画分镜》",
    author: "阿璃",
    authorId: "ali",
    avatar: "璃",
    type: "漫画分镜",
    image: reimuBirthdayImages.mangaStoryboard,
    gradient: "from-amber-100 via-pink-100 to-violet-200",
    tags: ["分镜", "小漫画", "接力"],
    description: "用轻量分镜整理生日小漫画的阅读节奏。",
  },
  {
    title: "《灵梦生日表情包》",
    author: "小满",
    authorId: "xiaoman",
    avatar: "满",
    type: "表情包",
    image: reimuBirthdayImages.stickerSheet,
    gradient: "from-cyan-100 via-sky-200 to-fuchsia-100",
    tags: ["表情包", "红白", "社群感"],
    description: "轻松的生日梗和赛钱箱梗，让活动不只停留在正式作品。",
  },
  {
    title: "《赛钱箱旁边的生日蛋糕》",
    author: "青禾",
    authorId: "qinghe",
    avatar: "青",
    type: "小插图",
    image: reimuBirthdayImages.birthdayCake,
    gradient: "from-amber-100 via-rose-100 to-emerald-100",
    tags: ["小插图", "生日蛋糕", "赛钱箱"],
    description: "适合放在短篇后的小过渡图，保留群友玩笑的现场感。",
  },
  {
    title: "《礼物清单》",
    author: "夜雀",
    authorId: "yeque",
    avatar: "夜",
    type: "短篇栏目",
    image: reimuBirthdayImages.giftChecklist,
    gradient: "from-violet-100 via-white to-amber-100",
    tags: ["短篇栏目", "礼物", "清单页"],
    description: "成员用一句话写下送给灵梦的礼物说明。",
  },
  {
    title: "《合辑封面分镜》",
    author: "阿璃",
    authorId: "ali",
    avatar: "璃",
    type: "封面分镜",
    image: reimuBirthdayImages.anthologyStoryboard,
    gradient: "from-red-100 via-white to-slate-200",
    tags: ["封面分镜", "过程稿", "合辑"],
    description: "为纪念合辑预留标题和作品目录位置。",
  },
  {
    title: "《灵梦生日图文接力合辑》",
    author: "阿璃 / 群体共创",
    authorId: "ali",
    avatar: "璃",
    type: "合辑封面",
    image: reimuBirthdayImages.anthologyCover,
    gradient: "from-rose-200 via-white to-sky-200",
    tags: ["合辑封面", "主视觉", "宣发"],
    description: "图文接力活动的合辑封面，适合作为活动记录馆封面和宣发主视觉。",
  },
] as const;

const imageByTitle = new Map<string, string>(reimuBirthdayWorks.map((work) => [work.title, work.image]));

export function getReimuBirthdayImage(title: string) {
  return imageByTitle.get(title) ?? imageByTitle.get(`《${title}》`);
}
